using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerRange : MonoBehaviour
{
    private Player player;

    private void Start()
    {
        player = GetComponentInParent<Player>(); // get ref to Player script in parent
    }

    // check for entering collider (e.g . enemy)
    private void OnTriggerEnter2D(Collider2D other)
    {
        player.NotifyRangeEntered(other); // notify Player script that it is in range
    }

    // check for exiting collider (e.g . enemy)
    private void OnTriggerExit2D(Collider2D other)
    {
        player.NotifyRangeExit(other); // notify Player script that it is out of range
    }
}
